name: Generate contribution snake

on:
  schedule:
    - cron: "17 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/snake.yml"

concurrency:
  group: contribution-snake
  cancel-in-progress: false

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#1ba881&color_dots=#edf4f1,#d0f1e5,#97e5ca,#58cfa8,#219675
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#74f8ce&color_dots=#101c29,#153e3c,#1b6557,#2b9c7c,#74f8ce

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
